language: cpp

jobs:
  allow_failures:
    # TODO: Remove this when OSX 10.15 is available in Travis
    - name: MacOS
      os: osx
      osx_image: xcode11.3

  include:
    - name: Ubuntu 18.04
      os: linux
      dist: bionic

    - name: Ubuntu 16.04
      os: linux
      dist: xenial

    - name: Windows 10
      os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\16.0\Bin"
        - PATH_FIX="C:\Windows\System32"

    - name: MacOS
      os: osx
      osx_image: xcode11.3

    - name: PX4 Test
      os: linux
      dist: bionic
      env:
        - PX4=true


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      sudo apt-get -y install git wget unzip;
      sudo apt-get -y install build-essential software-properties-common cmake rsync libboost-all-dev;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "No before_install actions for OSX";
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install visualstudio2019buildtools --package-parameters "--includeRecommended --includeOptional";
      choco install visualstudio2019-workload-vctools;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./setup.sh;
      ./build.sh || travis_terminate 1;
      echo "Starting Unity Build!";
      (cd Unity && ./build.sh 2> Unity_error.txt ||
        ((cat Unity_error.txt | grep -i "error:" -B 10 -A 10) && travis_terminate 1)
      );
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      export PATH=$MSBUILD_PATH:$PATH_FIX:$PATH;
      cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' amd64 '&&'
      build.cmd '&&'
      cd Unity '&&' build.cmd;
    elif  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ./setup.sh;
      ./build.sh || travis_terminate 1;
      echo "Starting Unity Build!";
      cd Unity && ./build.sh 2> Unity_error.txt || ((cat Unity_error.txt | grep -i "error:" -B 10 -A 10) && exit 1);
    fi

  - if [[ "$PX4" == "true" ]]; then
      echo "Starting PX4 Test";
      ./test/test_px4_sitl.sh;
    fi
